### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by suprafun** [kristenkwong/hiphop-lang#3]
Hello, under what license is this project released under ? I would like to study it to learn from it. Thank you.

**Comment by grahamhub** [comment]
Hi @suprafun , this was a school project that I ended up hopping on as a maintainer for afterwards to introduce extra functionality. While I can't know their original intent, I think it's safe to say we should be utilizing the MIT License. Feel free to fork / play around with it all you want! I'll update the repo accordingly
